---

- hosts: all
  become: true 
  tasks:
  - name: update repositort index
    apt:
      update_cache: yes
  - name: install_apache2 package 
    apt: 
      name: apache2
      state: latest
  
  - name: add php support
    apt: 
      name: libapache2-mod-php 
      state: latest
